name: app
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.4.0 <4.0.0'
dependencies:
  flutter:
    sdk: flutter
  easy_localization: ^3.0.7
  dio: ^5.4.3+1
  flutter_bloc: ^8.1.5
  get_it: ^7.7.0
  flutter_screenutil: ^5.9.3
  carousel_slider: ^4.2.1
  flutter_widget_from_html_core: ^0.14.12
  shimmer: ^3.0.0
  google_maps_flutter: ^2.6.1
  maps_launcher: ^2.2.1
  geocoding: ^3.0.0
  geolocator: ^12.0.0
  circular_countdown_timer: ^0.2.3
  shared_preferences: ^2.2.3
  animate_do: ^3.3.4
  image_picker: ^1.0.8
  pin_code_fields: ^8.0.1
  url_launcher: ^6.2.6
  flutter_svg: ^2.0.10+1
  animated_notch_bottom_bar: ^1.0.3
  firebase_core: ^3.0.0
  firebase_auth: ^5.0.0
  google_sign_in: ^6.2.1
  flutter_slidable: ^3.1.0
  quick_log: ^5.4.1
  qr_code_scanner: ^1.0.1
  firebase_database: ^11.0.1
  firebase_messaging: ^15.0.2
  awesome_notifications: ^0.9.3+1
  permission_handler: ^11.3.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
flutter:
  uses-material-design: true

  assets:
    - assets/fonts/
    - assets/svg/
    - assets/images/
    - assets/translations/

  fonts:
    - family: Tajawal
      fonts:
        - asset: assets/fonts/tajawal.ttf